### ISSUE TITLE
No module named sh

### ISSUE THREAD

**Issue by derari** [chrisma/tdd-for-students#1]
And travis be like

> ```
> $ ./travis/pull_tasks.py
> Traceback (most recent call last):
>   File "./travis/pull_tasks.py", line 4, in <module>
>     from sh import git, ErrorReturnCode, ErrorReturnCode_1, ErrorReturnCode_128
> ImportError: No module named sh
> ```

**Comment by chrisma** [comment]
pip install -r requirements.txt
Am 03.05.2016 11:59 schrieb "Arian Treffer" notifications@github.com:

**Comment by derari** [comment]
top!
